PlantItOut/Models/PlantCategory.cs
using System.Collections.Generic;

namespace PlantItOut.Models
{
    public class PlantCategory
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public List<Plant> Plants { get; set; }

        public PlantCategory(string name)
        {
            Name = name;
        }

        public PlantCategory()
        {
        }
    }
}

PlantItOut/Controllers/PlantCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlantItOut.Data;
using PlantItOut.Models;
using PlantItOut.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PlantItOut.Controllers
{
    [Authorize]
    public class PlantCategoryController : Controller
    {
        private PlantDbContext context;

        public PlantCategoryController(PlantDbContext dbContext)
        {
            context = dbContext;
        }

        //GET
        public IActionResult Index()
        {
            List<PlantCategory> plantCategories = context.PlantCategories.ToList();
            return View(plantCategories);
        }

        [HttpGet]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Create()
        {
            AddPlantCategoryViewModel addPlantCategoryViewModel = new AddPlantCategoryViewModel();
            return View(addPlantCategoryViewModel);
        }

        [HttpPost]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult ProcessCreatePlantCategoryForm(AddPlantCategoryViewModel addPlantCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                PlantCategory plantCategory = new PlantCategory()
                {
                    Name = addPlantCategoryViewModel.Name,
                };
                context.PlantCategories.Add(plantCategory);
                context.SaveChanges();

                return Redirect("/PlantCategory");
            }
            return View("Create", addPlantCategoryViewModel);
        }
    }
}

PlantItOut/Views/PlantCategory/Create.cshtml
@model PlantItOut.ViewModels.AddPlantCategoryViewModel

<h1>Add New Plant Category</h1>

<form asp-controller="PlantCategory" asp-action="ProcessCreatePlantCategoryForm" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <input type="submit" value="Add Plant Category" />
</form>

PlantItOut/Views/PlantCategory/Index.cshtml
@model List<PlantItOut.Models.PlantCategory>

<h1>All Plant Categories</h1>

@if (Model.Count == 0)
{
    <p>No Plant Categories yet!</p>
}
else
{
    <table class="table">
        <tr>
            <th>Id
            <th>Category Name</th>
        </tr>
        @foreach (var plantCategory in Model)
        {
            <tr>
                <td>@plantCategory.Id</td>
                <td>@plantCategory.Name</td>
            </tr>
        }
    </table>
}