PlantItOut/Models/Plant.cs
using System;
using System.Collections.Generic;

namespace PlantItOut.Models
{
    public class Plant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<PlantTag> PlantTags { get; set; }
        public PlantCategory Category { get; set; }
        public string ImageLink { get; set; }
        public int CategoryId { get; set; }
        public int TagId { get; set; }
        //public List<Comment> Comments { get; set; }

        public Plant()
        {
        }

        public Plant(string name, string description, int id)
        {
            Name = name;
            Description = description;
            Id = id;
            /*ImageLink = imageLink;*/
        }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Plant @plant &&
                Id == @plant.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

PlantItOut/Controllers/PlantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlantItOut.Data;
using PlantItOut.Models;
using PlantItOut.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PlantItOut.Controllers
{
    [Authorize]
    public class PlantController : Controller
    {
        private PlantDbContext context;

        public PlantController(PlantDbContext dbContext)
        {
            context = dbContext;
        }

        //GET 
        [Authorize]
        public IActionResult Index()
        {
            List<Plant> plants = context.Plants.ToList();
            return View(plants);
        }

        /*[Authorize(Roles= "Admin")]*/
        [Authorize]
        public IActionResult Add()
        {
            List<PlantCategory> plants = context.PlantCategories.ToList();
            AddPlantViewModel addPlantViewModel = new AddPlantViewModel(plants);

            return View(addPlantViewModel);
        }

        [HttpPost]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Add(AddPlantViewModel addPlantViewModel, string[] selectedTags)
        {
            if (ModelState.IsValid)
            {
                PlantCategory theCategory = context.PlantCategories.Find(addPlantViewModel.CategoryId);
                Plant newPlant = new Plant
                {
                    Name = addPlantViewModel.Name,
                    Description = addPlantViewModel.Description,
                    ImageLink = addPlantViewModel.ImageLink,
                    Category = theCategory
                };
                context.Plants.Add(newPlant);
                context.SaveChanges();

                foreach(string tag in selectedTags) 
                {
                    PlantTag plantTag = new PlantTag
                    {
                        Plant = newPlant,
                        PlantId = newPlant.Id,
                        TagId = int.Parse(tag),
                    };
                    context.PlantTags.Add(plantTag);
                }
                context.SaveChanges();
                return Redirect("/Plant");
            }

            return View(addPlantViewModel);
        }

        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Delete()
        {
            ViewBag.plants = context.Plants.ToList();
            return View();
        }

        [HttpPost]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Delete(int[] plantIds)
        {
            foreach (int plantId in plantIds)
            {
                Plant plant = context.Plants.Find(plantId);
                context.Plants.Remove(plant);
            }
            context.SaveChanges();
            return Redirect("/Plant");
        }

        [Authorize]
        public IActionResult Detail(int id)
        {
            Plant plant = context.Plants
                .Include(p => p.Category)
                .Single(p => p.Id == id);

            List<PlantTag> plantTags = context.PlantTags
                .Where(pt => pt.PlantId == id)
                .Include(PlantTag => PlantTag.Tag)
                .ToList();

            PlantDetailViewModel plantViewModel = new PlantDetailViewModel(plant, plantTags);
            return View(plantViewModel);
        }
    }
}

PlantItOut/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using PlantItOut.Data;
using PlantItOut.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using PlantItOut.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace PlantItOut.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        private PlantDbContext context;
        public TagController(PlantDbContext dbContext)
        {
            context = dbContext;
        }

        //GET
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag/");
            }
            return View("Add", tag);
        }

        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult AddPlant(int id)
        {
            Plant thePlant = context.Plants.Find(id);
            List<Tag> plantTags = context.Tags.ToList();

            AddPlantTagViewModel tagViewModel = new AddPlantTagViewModel(thePlant, plantTags);
            return View(tagViewModel);
        }

        [HttpPost]
        /*[Authorize(Roles = "Admin")]*/
        [Authorize]
        public IActionResult AddPlant(AddPlantTagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                int plantId = tagViewModel.PlantId;
                int tagId = tagViewModel.TagId;

                List<PlantTag> exsistingTags = context.PlantTags
                    .Where(pt => pt.PlantId == plantId)
                    .Where(pt => pt.TagId == tagId)
                    .ToList();

                if (exsistingTags.Count == 0)
                {
                    PlantTag plantTag = new PlantTag
                    {
                        PlantId = plantId,
                        TagId = tagId
                    };
                    context.PlantTags.Add(plantTag);
                    context.SaveChanges();
                }
                return Redirect("/Plant/Detail/" + plantId);
            }
            return View(tagViewModel);
        }

        /*public IActionResult Detail(int id)
        {
            List<PlantTag> plantTags = context.PlantTags
                .Where(pt => pt.TagId == id)
                .Include(pt => pt.Plant)
                .Include(pt => pt.Tag)
                .ToList();

            return View(plantTags);
        }*/
        [Authorize]
        public IActionResult Delete()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int[] tagIds)
        {
            foreach (int tagId in tagIds)
            {
                Tag tag = context.Tags.Find(tagId);
                context.Tags.Remove(tag);
            }
            context.SaveChanges();

            List<Tag> tagList = context.Tags.ToList();

            return View("Index", tagList);
        }
    }
}

PlantItOut/Views/Plant/Add.cshtml
@model PlantItOut.ViewModels.AddPlantViewModel;

<h1>Add A new Plant!</h1>

<form asp-controller="Plant" asp-action="Add" method="post">

    <div class="form-group">
        <h6>Plant Name</h6>
        @*<label asp-for="Name"></label>*@
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <h6>Plant Description</h6>
        @*<label asp-for="Description"></label>*@
        <textarea name="@Html.NameFor(m=>m.Description)" rows="4" cols="50"></textarea>
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <h6>Plant Category</h6>
        @*<label asp-for="CategoryId">Category</label>*@
        <select asp-for="CategoryId" asp-items="Model.PlantCategories"></select>
    </div>
    <div class="form-group">
        <h6>Image Link</h6>
        <input asp-for="ImageLink" />
        <span asp-validation-for="ImageLink"></span>
    </div>

        <a asp-controller="plantCategory" asp-action="Create">Create a New Category</a>

    <input type="submit" value="Add New Plant" />
</form>

PlantItOut/Views/Plant/Delete.cshtml
<h1>Delete A Plant</h1>

<form method="post">
    @foreach (var plant in ViewBag.plants)
    {
        <div class="form-group">
            <label>
                <span>@plant.Name</span>
                <input type="checkbox" name="plantIds" value="@plant.Id" class="form-control">
            </label>
        </div>
    }

    <input type="submit" value="Delete Selected Plants" class="btn btn-danger">

</form>

PlantItOut/Views/Plant/Detail.cshtml
@model PlantItOut.ViewModels.PlantDetailViewModel

<form method="post">
    <h1>@Model.Name</h1>
    <div class="img">
        <img src="@Model.ImageLink" width="400" height="600"/>
    </div>

    <table class="table">
        <tr>
            <th>Description</th>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>@Model.Category</td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>@Model.TagText</td>
        </tr>
    </table>
    <a asp-controller="Tag" asp-action="AddPlant" asp-route-id="@Model.PlantId">Add Tags to Plant</a>
</form>


@*
Figure out how to add a comment option underneath 
the available plant details so that a user can add and see 
previous care tips that have been shared on each plant.
*@  

@*<h3>Community CareTips</h3>*@

PlantItOut/Views/Plant/Index.cshtml
@model List<PlantItOut.Models.Plant>

<h1>HousePlants!</h1>

<p>
    <a asp-controller="Plant" asp-action="Add">Add Plant</a>
</p>
<p>
    <a asp-controller="Plant" asp-action="Delete">Delete A Plant</a>
</p>

@if (Model.Count == 0)
{
    <p>No plants added yet!</p>
}
else
{
    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            @*<th>
                Category
            </th>*@
        </tr>
    @foreach (var plant in Model)
        {
            <tr>
                <td>@plant.Id</td>
                <td><a asp-controller="Plant" asp-action="Detail" asp-route-id="@plant.Id">@plant.Name</a></td>
                <td>@plant.Description</td>
                @*<td>@plant.CategoryId</td>*@
            </tr>
        }
    </table>
}